# Generated by Django 3.0.3 on 2020-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0002_auto_20200528_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='Workprogres',
        ),
        migrations.AddField(
            model_name='work',
            name='workprogres',
            field=models.CharField(default='B', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='desg',
            field=models.CharField(max_length=250),
        ),
    ]
