# Generated by Django 2.0 on 2020-04-30 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0003_auto_20200429_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDate', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detection.User')),
                ('workname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detection.Work')),
            ],
        ),
    ]
