# Generated by Django 2.0 on 2020-04-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0004_work_workassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50)),
                ('workDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Detection.WorkAssign')),
            ],
        ),
    ]
