# Generated by Django 2.0 on 2020-04-30 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0005_workprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Detection.User'),
            preserve_default=False,
        ),
    ]
