# Generated by Django 3.0.3 on 2020-02-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=250)),
                ('appname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='Detection.App')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uname', to='Detection.User')),
            ],
        ),
    ]
