# Generated by Django 2.0 on 2020-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockwords', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
